# Use root/example as user/password credentials
version: '3.2'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "mysql_volume:/var/lib/mysql"
    networks:
      - mysql_net
    environment:
      MYSQL_ROOT_PASSWORD: example
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8880:8080
    networks:
      - mysql_net
    
networks:
  mysql_net:
volumes:
  mysql_volume:
