version: "3.6"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper
    ports:
      - "2181:2181"
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  broker1:
    extends:
      file: broker.yml
      service: broker
    deploy:
      placement:
        constraints: 
           - "node.hostname==docker01"
    volumes:
      - "kafka_data:/bitnami"
      - "broker_1:/opt/bitnami/kafka/config"
  broker2:
    extends:
      file: broker.yml
      service: broker
    deploy:
      placement:
        constraints: 
           - "node.hostname==docker02"
    volumes:
      - "kafka_data:/bitnami"
      - "broker_2:/opt/bitnami/kafka/config"
  broker3:
    extends:
      file: broker.yml
      service: broker
    deploy:
      placement:
        constraints: 
           - "node.hostname==docker03"
    volumes:
      - "kafka_data:/bitnami"
      - "broker_3:/opt/bitnami/kafka/config"
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  broker_1:
    driver: local
      driver_opts:
        o: bind
        type: none
        device: ./config/broker_1
  broker_2:
    driver: local
      driver_opts:
        o: bind
        type: none
        device: ./config/broker_2
  broker_3:
    driver: local
      driver_opts:
        o: bind
        type: none
        device: ./config/broker_3
