version: "3.6"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper
    ports:
      - "2181:2181"
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  broker1:
    extends:
      file: broker.yml
      service: broker
    deploy:
      placement:
        constraints: 
           - "node.hostname==docker01"
    volumes:
      - "kafka_data:/bitnami"
      - type: bind
        source: ./config/broker_1
        target: /opt/bitnami/kafka/config
  broker2:
    extends:
      file: broker.yml
      service: broker
    deploy:
      placement:
        constraints: 
           - "node.hostname==docker02"
    volumes:
      - "kafka_data:/bitnami"
      - type: bind
        source: ./config/broker_2
        target: /opt/bitnami/kafka/config
  broker3:
    extends:
      file: broker.yml
      service: broker
    deploy:
      placement:
        constraints: 
           - "node.hostname==docker03"
    volumes:
      - "kafka_data:/bitnami"
      - type: bind
        source: ./config/broker_3
        target: /opt/bitnami/kafka/config

volumes:
  zookeeper_data:
  kafka_data:
