version: "3.6"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper
    ports:
      - "2181:2181"
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  broker:
    image: docker.io/bitnami/kafka
    ports:
       - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    deploy:
      replicas: 3
      placement:
        constraints: 
           - node.role==worker
    volumes:
      - "kafka_data:/bitnami"
     
volumes:
  zookeeper_data:
  kafka_data:
